export const POST_REQUEST_REGISTRATION_START = "POST_REQUEST_REGISTRATION_START";
export const POST_REQUEST_REGISTRATION_SUCCESS = "POST_REQUEST_REGISTRATION_SUCCESS";
export const POST_REQUEST_REGISTRATION_ERROR = "POST_REQUEST_REGISTRATION_ERROR";

export const POST_REQUEST_LOGIN_START = "POST_REQUEST_LOGIN_START";
export const POST_REQUEST_LOGIN_SUCCESS = "POST_REQUEST_LOGIN_SUCCESS";
export const POST_REQUEST_LOGIN_ERROR = "POST_REQUEST_LOGIN_ERROR";

export const SWITCH_LOGIN_MODAL_OPEN_STATE = "SWITCH_LOGIN_MODAL_OPEN_STATE";
export const ACTION_LOGOUT = "ACTION_LOGOUT";

export const GET_REQUEST_PRODUCTS_START = "GET_REQUEST_PRODUCTS_START";
export const GET_REQUEST_PRODUCTS_SUCCESS = "GET_REQUEST_PRODUCTS_SUCCESS";
export const GET_REQUEST_PRODUCTS_ERROR = "GET_REQUEST_PRODUCTS_ERROR";

export const DELETE_REQUEST_PRODUCTS_START = "DELETE_REQUEST_PRODUCTS_START";
export const DELETE_REQUEST_PRODUCTS_SUCCESS = "DELETE_REQUEST_PRODUCTS_SUCCESS";
export const DELETE_REQUEST_PRODUCTS_ERROR = "DELETE_REQUEST_PRODUCTS_ERROR";

export const PATCH_REQUEST_PRODUCTS_START = "PATCH_REQUEST_PRODUCTS_START";
export const PATCH_REQUEST_PRODUCTS_SUCCESS = "PATCH_REQUEST_PRODUCTS_SUCCESS";
export const PATCH_REQUEST_PRODUCTS_ERROR = "PATCH_REQUEST_PRODUCTS_ERROR";

export const SET_EDITING_PRODUCT = "SET_EDITING_PRODUCT";
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS";
