export const GET_REQUEST_PRODUCTS_START = "GET_REQUEST_PRODUCTS_START";
export const GET_REQUEST_PRODUCTS_SUCCESS = "GET_REQUEST_PRODUCTS_SUCCESS";
export const GET_REQUEST_PRODUCTS_ERROR = "GET_REQUEST_PRODUCTS_ERROR";