export const GET_REQUEST_PRODUCTS_START = "GET_REQUEST_PRODUCTS_START";
export const GET_REQUEST_PRODUCTS_SUCCESS = "GET_REQUEST_PRODUCTS_SUCCESS";
export const GET_REQUEST_PRODUCTS_ERROR = "GET_REQUEST_PRODUCTS_ERROR";

export const DELETE_REQUEST_PRODUCTS_START = "DELETE_REQUEST_PRODUCTS_START";
export const DELETE_REQUEST_PRODUCTS_SUCCESS = "DELETE_REQUEST_PRODUCTS_SUCCESS";
export const DELETE_REQUEST_PRODUCTS_ERROR = "DELETE_REQUEST_PRODUCTS_ERROR";

export const PUT_REQUEST_PRODUCTS_START = "PUT_REQUEST_PRODUCTS_START";
export const PUT_REQUEST_PRODUCTS_SUCCESS = "PUT_REQUEST_PRODUCTS_SUCCESS";
export const PUT_REQUEST_PRODUCTS_ERROR = "PUT_REQUEST_PRODUCTS_ERROR";

export const SET_EDITING_PRODUCT = "SET_EDITING_PRODUCT";